name: build-and-publish

on:
  push:
    branches: [main, dev_kolin]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        pyver: [cp36, cp37, cp38, cp39, cp310, cp311, cp312]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "true"
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.2
        env:
          CIBW_BUILD: ${{ matrix.pyver }}-*
      - name: Upload wheel artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-${{ matrix.pyver }}-${{ strategy.job-index }}
          path: wheelhouse/*

  build-sdist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "true"
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install pypa/build
        run: "python -m pip install build --user"
      - name: Build a source tarball
        run: "python -m build --sdist"
      - name: Upload sdist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*

  nightly-release:
    if: startsWith(github.ref, 'refs/heads/')  # if a commit is pushed
    needs: [build, build-sdist]
    runs-on: ubuntu-latest
    permissions:
      contents: write  # create nightly release
    steps:
      - name: Download wheel artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist/
          merge-multiple: true
      - name: Update Nightly Release
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly
          name: 'Nightly Release'
          prerelease: true
          body: 'MPlib development nightly release.'
          files: |
            dist/*
